"use strict";
const token = document.querySelector('meta[name="preflight-token"]').content;
const ui = {tab:"overview", episode:0, frame:0, exclude:new Set(), run:null, compare:new Set(),
  form:{fraction:.2,seed:7,steps:200,batch:16,lr:.001,chunk:4,prepared:"",backend:"tiny",python:"",resume:""}};
let state = null, notice = "", refreshing = false;
const $ = id => document.getElementById(id);
const esc = x => String(x ?? "").replace(/[&<>"']/g, c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num = (x,d=3) => Number.isFinite(x)?x.toLocaleString(undefined,{maximumFractionDigits:d}):"—";
const pill = (x,label=x) => `<span class="pill ${esc(x)}">${esc(label)}</span>`;
const labels = {overview:"数据总览",episodes:"轨迹检查",prepare:"数据准备",train:"训练与比较"};
const kindLabels = {analyze:"数据分析",prepare:"训练准备",export:"数据导出",train:"小型 VLA 训练","smol-plan":"SmolVLA 计划"};
const busy = () => state?.jobs.some(j=>["running","queued"].includes(j.status));
const disabled = () => busy()?"disabled":"";
function showNotice(message){notice=message;$("notice").hidden=!message;$("notice").className="notice";$("notice").textContent=message;}
async function api(path,body){const r=await fetch(path,body?{method:"POST",headers:{"Content-Type":"application/json","X-Preflight-Token":token},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||r.statusText);return data;}
async function start(body){try{showNotice("");await api("/api/jobs",body);await refresh();}catch(e){showNotice(e.message);}}
function download(name,data){const a=document.createElement("a");const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function svgChart(series,{height=210,xLabel="frame"}={}){
 const colors=["#2864dd","#15a083","#c98624","#b85a9d"];const valid=series.filter(s=>s.values?.length);
 if(!valid.length)return '<div class="empty">暂无曲线数据</div>';
 const all=valid.flatMap(s=>s.values.map(v=>v[1])).filter(Number.isFinite), xs=valid.flatMap(s=>s.values.map(v=>v[0]));
 let lo=Math.min(...all),hi=Math.max(...all);if(hi-lo<1e-9){hi+=.5;lo-=.5;}const minX=Math.min(...xs),maxX=Math.max(...xs);
 const X=x=>44+(x-minX)/(maxX-minX||1)*536,Y=y=>height-30-(y-lo)/(hi-lo)*(height-48);
 let out=`<svg class="chart" viewBox="0 0 600 ${height}" role="img" aria-label="${esc(valid.map(s=>s.name).join(', '))}">`;
 for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;out+=`<line x1="44" x2="580" y1="${Y(v)}" y2="${Y(v)}" stroke="#e8eef5"/><text x="36" y="${Y(v)+4}" text-anchor="end">${num(v,3)}</text>`;}
 out+=`<text x="44" y="${height-8}">${num(minX,0)}</text><text x="580" y="${height-8}" text-anchor="end">${num(maxX,0)} ${esc(xLabel)}</text>`;
 valid.forEach((s,i)=>{out+=`<polyline fill="none" stroke="${colors[i%4]}" stroke-width="2" ${s.dashed?'stroke-dasharray="5 4"':''} points="${s.values.map(([x,y])=>`${X(x)},${Y(y)}`).join(' ')}"/>`;});
 return out+`</svg><div class="legend">${valid.map((s,i)=>`<span><i style="background:${colors[i%4]}"></i>${esc(s.name)}</span>`).join('')}</div>`;
}
function kpi(label,value,note){return `<div class="card"><div class="kpi-label">${label}</div><div class="kpi-number">${value}</div><div class="muted">${note}</div></div>`;}
function overview(){
 const a=state.analysis, p=a?.profile, errors=a?.audit.findings.filter(x=>x.severity==="error").reduce((n,x)=>n+x.count,0);
 return `<div class="grid kpis">${kpi("轨迹 / EPISODES",num(state.episodes,0),"以完整轨迹为单位划分")}${kpi("样本帧 / FRAMES",num(state.frames,0),`${p?.fps||"—"} Hz · ${esc(p?.version||"")}`)}${kpi("检查错误",errors===undefined?"—":num(errors,0),a?`${a.audit.findings.length} 类诊断结果`:"分析完成后显示")}${kpi("训练实验",state.runs.length,"记录配置、指标与检查点")}</div>
 <div class="grid two"><section class="card"><div class="section-head"><h2>每条轨迹的动作变化</h2><span class="muted">全量数值计算</span></div>${svgChart((p?[{name:"平均相邻动作变化",values:p.episodes.map(e=>[e.episode,e.action_change_mean||0])},{name:"最大相邻动作变化",values:p.episodes.map(e=>[e.episode,e.action_change_max||0])}]:[]),{xLabel:"episode"})}<p class="muted">变化幅度取动作差的 L2 范数。它是排查线索，不是自动质量评分。</p></section>
 <section class="card"><h2>下一步怎么做</h2><div class="steps"><div class="step"><span class="step-number">1</span><div><b>检查轨迹与视觉输入</b><p>回放图像，定位数值异常和重复轨迹。</p></div></div><div class="step"><span class="step-number">2</span><div><b>准备可复现训练数据</b><p>按轨迹划分，统计量只使用训练集。</p></div></div><div class="step"><span class="step-number">3</span><div><b>运行并比较实验</b><p>真实小型 VLA 训练，保存采样记录和离线评估。</p></div></div></div><button class="wide-button" data-go="episodes">检查轨迹 →</button></section></div>
 <section class="card block-gap"><div class="section-head"><h2>预检发现</h2><button class="secondary small" id="download-report" ${a?"":"disabled"}>下载分析 JSON</button></div>${!a?'<p class="muted">正在分析…</p>':a.audit.findings.length?`<div class="table-wrap"><table><thead><tr><th>检查项</th><th>结果</th><th>定位与建议</th></tr></thead><tbody>${a.audit.findings.map(f=>`<tr><td class="code">${esc(f.code)}</td><td>${pill(f.severity)} × ${f.count}</td><td>${esc(f.message)}<p class="muted">${esc(f.suggestion)}</p><details><summary>查看证据</summary><pre>${esc(JSON.stringify(f.examples,null,2))}</pre></details></td></tr>`).join('')}</tbody></table></div>`:'<div class="callout">已完成声明范围内的检查，未发现错误。未执行的检查与限制仍需查看报告。</div>'}</section>`;
}
function episodeView(){
 const episodes=state.analysis?.profile.episodes||[];const ep=episodes.find(x=>x.episode===ui.episode)||episodes[0];if(ep)ui.episode=ep.episode;
 const series=ep?.preview?.action||[];
 return `<div class="grid two"><section class="card"><div class="section-head"><h2>轨迹列表</h2><span class="muted">已选排除 ${ui.exclude.size} 条</span></div><div class="table-wrap"><table><thead><tr><th>排除</th><th>轨迹</th><th>帧数</th><th>最大变化</th><th>无效行</th></tr></thead><tbody>${episodes.map(e=>`<tr class="${e.episode===ui.episode?'selected':''}"><td><input aria-label="排除轨迹 ${e.episode}" type="checkbox" data-exclude="${e.episode}" ${ui.exclude.has(e.episode)?'checked':''}></td><td><button class="secondary small" data-episode="${e.episode}">Episode ${e.episode}</button></td><td>${e.frames}</td><td>${num(e.action_change_max)}</td><td>${e.invalid_rows}</td></tr>`).join('')}</tbody></table></div><div class="tools"><button id="export" ${disabled()}>导出所选之外的轨迹</button><span class="muted">创建新数据集，不修改源文件</span></div></section>
 <section class="card"><div class="section-head"><h2>Episode ${ep?.episode??'—'} · 视觉预览</h2><span id="frame-label" class="muted">Frame ${ui.frame}</span></div><div class="image-box">${state.cameras.length&&ep?`<img id="episode-image" alt="选中帧的相机图像" src="${imageUrl()}">`:'<span class="muted">此数据集没有视觉特征</span>'}<span class="image-note">${esc(state.cameras[0]||"numeric-only")}</span></div><input aria-label="预览帧" id="frame-slider" type="range" min="0" max="${Math.max(0,(ep?.frames||1)-1)}" value="${ui.frame}"><p class="muted">${esc(ep?.tasks.join(' · ')||"无轨迹指令")}</p></section></div>
 <div class="grid equal block-gap"><section class="card"><h2>动作曲线 · 前四个维度</h2>${svgChart(Array.from({length:Math.min(4,series[0]?.length||0)},(_,d)=>({name:`action[${d}]`,values:series.map((v,i)=>[ep.preview_frames[i],v[d]])})))}</section><section class="card"><h2>时间偏移探索</h2>${svgChart(ep?.lag_probe?.length?[{name:"action[t] / state[t+lag] 相关性",values:ep.lag_probe.map(x=>[x.lag_frames,x.correlation])}]:[],{xLabel:"lag frames"})}<p class="muted">仅同维度数据计算。相关性不能确定真实延迟，不会自动平移动作。</p></section></div>`;
}
function imageUrl(){return `/api/image?episode=${ui.episode}&frame=${ui.frame}&camera=${encodeURIComponent(state.cameras[0]||'')}`;}
function preparation(){const bundles=state.prepared,p=state.analysis?.profile;
 return `<div class="grid equal"><section class="card"><h2>创建训练准备包</h2><p class="muted">固定轨迹划分，重新计算训练集统计量，记录数据文件指纹。</p><div class="form-grid"><label class="field">验证集比例<input data-form="fraction" type="number" min=".01" max=".9" step=".05" value="${ui.form.fraction}"></label><label class="field">随机种子<input data-form="seed" type="number" min="0" value="${ui.form.seed}"></label></div><div class="callout">相同数值与任务标签的轨迹会留在同一组，减少重复轨迹跨训练/验证集的风险。不会执行图像语义去重。</div><button id="prepare" ${disabled()}>创建准备包</button></section>
 <section class="card"><h2>数据诊断摘要</h2><div class="metric-row"><span>数值重复组</span><b>${p?.duplicate_groups.length??'—'}</b></div><div class="metric-row"><span>当前排除选择</span><b>${ui.exclude.size} 条</b></div><div class="metric-row"><span>统计量拟合范围</span><b>训练 episode</b></div><div class="metric-row"><span>源文件</span><b>保持不变</b></div><p class="muted">排除选择只用于“导出”按钮。训练准备始终使用当前源数据集；要训练清洗后的数据，请为导出目录另开工作台。</p>${p?.duplicate_groups.length?`<pre>${esc(JSON.stringify(p.duplicate_groups))}</pre>`:''}</section></div>
 <section class="card block-gap"><h2>已保存的准备包</h2>${bundles.length?`<table><thead><tr><th>ID</th><th>训练轨迹</th><th>验证轨迹</th><th>种子</th><th></th></tr></thead><tbody>${bundles.map(b=>`<tr><td class="mono">${esc(b.id)}</td><td>${b.split.train.length}</td><td>${b.split.validation.length}</td><td>${b.split.seed}</td><td><button class="secondary small" data-bundle="${esc(b.id)}">用于训练 →</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">还没有准备包。先完成一次数据分析，然后点击创建。</div>'}</section>`;
}
function training(){const runs=state.runs,selected=runs.find(r=>r.id===ui.run)||runs.at(-1);if(selected)ui.run=selected.id;
 const preparedOptions=state.prepared.map(b=>`<option value="${esc(b.id)}" ${ui.form.prepared===b.id?'selected':''}>${esc(b.id)} · ${b.split.train.length}/${b.split.validation.length} episodes</option>`).join('');
 const compared=runs.filter(r=>ui.compare.has(r.id)),same=new Set(compared.map(r=>r.bundle_digest)).size<=1;
 return `<div class="grid two"><section class="card"><div class="section-head"><h2>训练配置</h2>${pill('running','可复现实验')}</div><div class="form-grid"><label class="field full">训练后端<select data-form="backend"><option value="tiny" ${ui.form.backend==='tiny'?'selected':''}>Tiny VLA · 本机实际训练与离线评估</option><option value="smol" ${ui.form.backend==='smol'?'selected':''}>SmolVLA · 导出训练集并生成外部启动计划</option></select></label><label class="field full">准备包<select data-form="prepared"><option value="">请选择准备包</option>${preparedOptions}</select></label><label class="field">总训练步数<input data-form="steps" type="number" min="1" max="100000" value="${ui.form.steps}"></label><label class="field">Batch size<input data-form="batch" type="number" min="1" value="${ui.form.batch}"></label><label class="field">学习率<input data-form="lr" type="number" min=".000001" step=".0001" value="${ui.form.lr}"></label><label class="field">动作块长度<input data-form="chunk" type="number" min="1" max="64" value="${ui.form.chunk}"></label><label class="field full">从检查点继续（仅 Tiny VLA）<select data-form="resume"><option value="">新实验</option>${runs.filter(r=>r.completed_steps).map(r=>`<option value="${esc(r.id)}" ${ui.form.resume===r.id?'selected':''}>${esc(r.id)} · step ${r.completed_steps}</option>`).join('')}</select></label>${ui.form.backend==='smol'?`<label class="field full">安装 LeRobot 的 Python 路径<input data-form="python" type="text" placeholder="例如 /path/to/lerobot-env/bin/python" value="${esc(ui.form.python)}"></label>`:''}</div><button id="train" ${disabled()}>${ui.form.backend==='smol'?'生成 SmolVLA 计划':'开始训练'}</button></section>
 <section class="card"><h2>实验说明</h2><div class="callout amber">Tiny VLA 是随机初始化的小型图像 + 文本 + 状态模型，用于实测训练流程；不是预训练大模型。</div><div class="steps"><div class="step"><span class="step-number">✓</span><div><b>真正执行梯度更新</b><p>训练集归一化、动作块 mask、验证集离线 MAE。</p></div></div><div class="step"><span class="step-number">✓</span><div><b>保存可检查的结果</b><p>模型与优化器检查点、实际采样 trace、配置、损失记录。</p></div></div><div class="step"><span class="step-number">!</span><div><b>SmolVLA 需要独立环境</b><p>生成计划不启动大模型。可在终端显式运行 smol-launch；请先在目标环境实测显存占用。</p></div></div></div></section></div>
 <section class="card block-gap"><div class="section-head"><h2>实验记录</h2><span class="muted">勾选可比较实验</span></div>${runs.length?`<div class="table-wrap"><table><thead><tr><th>比较</th><th>实验</th><th>状态</th><th>步数</th><th>验证 MAE</th><th>均值基线 MAE</th><th>耗时</th></tr></thead><tbody>${runs.map(r=>`<tr class="${r.id===ui.run?'selected':''}"><td><input type="checkbox" aria-label="比较实验 ${esc(r.id)}" data-compare="${esc(r.id)}" ${ui.compare.has(r.id)?'checked':''}></td><td><button class="secondary small" data-run="${esc(r.id)}">${esc(r.id)}</button></td><td>${pill(r.status)}</td><td>${r.completed_steps??r.metrics.at(-1)?.step??0}</td><td>${num(r.validation?.mae,5)}</td><td>${num(r.validation?.mean_action_baseline_mae,5)}</td><td>${num(r.seconds,1)} s</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">还没有实验。准备数据后可以运行第一轮训练。</div>'}
 ${compared.length>=2?`<div class="callout ${same?'':'amber'}">${same?'这些实验使用相同准备包，可对照离线 MAE。':'这些实验使用不同准备包，验证 MAE 不可直接比较。'}<button class="secondary small" id="download-comparison">导出比较</button></div>`:''}</section>
 <div class="grid equal block-gap"><section class="card"><h2>归一化训练损失</h2>${svgChart(selected?[{name:'train loss',values:selected.metrics.map(x=>[x.step,x.train_loss])}]:[],{xLabel:'step'})}</section><section class="card"><h2>验证集 MAE · 原始动作单位</h2>${svgChart((compared.length>=2?compared:selected?[selected]:[]).map(r=>({name:r.id,values:r.metrics.map(x=>[x.step,x.validation_mae])})),{xLabel:'step'})}</section></div>
 ${selected?.validation?`<section class="card block-gap"><h2>所选实验的验证结果</h2><div class="run-metrics"><div><b>${num(selected.initial_validation?.mae,5)}</b><span>训练前 MAE</span></div><div><b>${num(selected.validation.mae,5)}</b><span>训练后 MAE</span></div><div><b>${num(selected.parameters,0)}</b><span>参数量</span></div><div><b>${num(selected.normalization_roundtrip_max_error,12)}</b><span>归一化往返误差</span></div></div>${(selected.diagnostics||[]).map(d=>`<div class="callout amber">${esc(d)}</div>`).join('')}<p class="muted">最佳验证 MAE：${num(selected.best_validation?.mae,5)}，step ${selected.best_validation?.step??'—'}，已保存 best.pt（含初始模型候选；只在日志步评估）。</p><p class="muted">评估每个观测对应的动作块首个动作。这里没有计算机器人任务成功率。</p></section>`:''}`;
}
function render(){if(!state)return;$("page-title").textContent=labels[ui.tab];$("version").textContent=`v${state.version} alpha`;$("dataset-line").innerHTML=`<b>${esc(state.dataset)}</b> <span> / ${esc(state.dataset_root)}</span>`;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===ui.tab));
 const active=state.jobs.find(j=>['running','queued'].includes(j.status));const recent=state.jobs.at(-1);
 $("job-bar").innerHTML=active?`<div class="job"><div><span class="dot"></span><b>${esc(kindLabels[active.kind])}</b> <small>${active.metrics.length?'step '+active.metrics.at(-1).step:'处理中…'}</small></div>${active.kind==='train'?`<button class="secondary small" data-cancel="${esc(active.id)}">停止并保存</button>`:''}</div>`:recent?.status==='failed'?`<div class="notice">${esc(kindLabels[recent.kind])}失败：${esc(recent.error)}</div>`:recent?.artifact?`<div class="dataset-line">最近产物：<span class="mono">${esc(state.workspace)} / ${esc(recent.artifact)}</span></div>`:'';
 $("content").innerHTML=({overview,episodes:episodeView,prepare:preparation,train:training}[ui.tab])();bind();$("refresh").disabled=busy();showNotice(notice);
}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{ui.tab=b.dataset.go;render();});document.querySelectorAll('[data-episode]').forEach(b=>b.onclick=()=>{ui.episode=+b.dataset.episode;ui.frame=0;render();});document.querySelectorAll('[data-exclude]').forEach(b=>b.onchange=()=>{b.checked?ui.exclude.add(+b.dataset.exclude):ui.exclude.delete(+b.dataset.exclude);render();});document.querySelectorAll('[data-bundle]').forEach(b=>b.onclick=()=>{ui.form.prepared=b.dataset.bundle;ui.tab='train';render();});document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>{ui.run=b.dataset.run;render();});document.querySelectorAll('[data-compare]').forEach(b=>b.onchange=()=>{b.checked?ui.compare.add(b.dataset.compare):ui.compare.delete(b.dataset.compare);render();});document.querySelectorAll('[data-form]').forEach(input=>input.oninput=input.onchange=()=>{ui.form[input.dataset.form]=input.type==='number'?+input.value:input.value;if(input.dataset.form==='backend')render();});
 if($("frame-slider"))$("frame-slider").oninput=e=>{ui.frame=+e.target.value;$("frame-label").textContent=`Frame ${ui.frame}`;if($("episode-image"))$("episode-image").src=imageUrl();};
 if($("episode-image"))$("episode-image").onerror=()=>showNotice('此帧无法读取。请检查图像数据或安装可选的 Pillow/PyAV 依赖。');
 if($("download-report"))$("download-report").onclick=()=>download('vla-analysis.json',state.analysis);
 if($("prepare"))$("prepare").onclick=()=>start({kind:'prepare',validation_fraction:ui.form.fraction,seed:ui.form.seed});
 if($("export"))$("export").onclick=()=>start({kind:'export',exclude:[...ui.exclude]});
 if($("train"))$("train").onclick=()=>{if(!ui.form.prepared)return showNotice('请先在数据准备页面创建并选择准备包。');start({kind:ui.form.backend==='smol'?'smol-plan':'train',prepared_id:ui.form.prepared,steps:ui.form.steps,batch_size:ui.form.batch,learning_rate:ui.form.lr,chunk_size:ui.form.chunk,seed:ui.form.seed,resume_id:ui.form.resume||null,python:ui.form.python||null});};
 document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await api('/api/cancel',{id:b.dataset.cancel});showNotice('已请求停止，将在当前训练步完成后保存。');}catch(e){showNotice(e.message);}});
 if($("download-comparison"))$("download-comparison").onclick=()=>download('run-comparison.json',state.runs.filter(r=>ui.compare.has(r.id)));
}
async function refresh(){if(refreshing)return;refreshing=true;try{state=await api('/api/state');$("connection").textContent='已连接 · 本机';$("connection").className='pill';if(!ui.form.prepared&&state.prepared.length)ui.form.prepared=state.prepared.at(-1).id;if(!document.activeElement?.matches('input,select'))render();}catch(e){$("connection").textContent='连接中断';$("connection").className='pill failed';showNotice(e.message);}finally{refreshing=false;}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{ui.tab=b.dataset.tab;render();});$("refresh").onclick=()=>start({kind:'analyze'});refresh();setInterval(refresh,1800);
